### ISSUE TITLE
Add support for operators

### ISSUE THREAD

**Issue by romac** [epfl-lara/scallion#4]
Basically port [my port for Fastparse](https://gist.github.com/romac/100b78357b17605cf21edfe04a9b1a39) of [Megaparsec's operators](http://hackage.haskell.org/package/megaparsec-6.5.0/docs/src/Text.Megaparsec.Expr.html#Operator) :p

**Comment by redelmann** [comment]
Support is already there, but in a separate trait (scallion.parsing.Operators).

See https://github.com/epfl-lara/scallion/blob/881891a3fd4f7b75cdec8dd0a55dfb13081a0fe8/src/main/scala/scallion/parsing/Parsers.scala#L697

**Comment by redelmann** [comment]
Any suggestions on how to make this more visible?

**Comment by romac** [comment]
Sorry, my bad, I didn't notice.

> Any suggestions on how to make this more visible?

Perhaps add an example to the README which exercises that feature?

On a semi-related note, it might be good to publish the ScalaDoc somewhere, especially since you have taken great care of documenting everything :)

**Comment by redelmann** [comment]
Live since this morning: https://epfl-lara.github.io/scallion/ ;)
I need to add a link in the README.

Good idea. I'll also link to more clearly in the documentation.

**Comment by romac** [comment]
Nice!

Couple other suggestions:

- I like when projects link directly to their package instead of `root`, ie. https://epfl-lara.github.io/scallion/scallion/index.html
- Do you know how to include the sources in the generated ScalaDoc? It's nice imho to be able to jump in the source from the docs (using the "Source" link as in eg. https://www.scala-lang.org/api/2.12.3/scala/collection/immutable/List.html)

**Comment by redelmann** [comment]
I added documentation for the root package and added links.
